swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /proyecto-academico/:
    get:
      tags:
      - proyecto-academico
      description: get ConsultaProyectoAcademico
      operationId: ProyectoAcademicoController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConsultaProyectoAcademico'
        "404":
          description: not found resource
    post:
      tags:
      - proyecto-academico
      description: Crear Proyecto
      operationId: ProyectoAcademicoController.PostProyecto
      parameters:
      - in: body
        name: body
        description: body Agregar Proyecto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
  /proyecto-academico/{id}:
    get:
      tags:
      - proyecto-academico
      description: get ConsultaProyectoAcademico by id
      operationId: ProyectoAcademicoController.GetOnePorId
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConsultaProyectoAcademico'
        "404":
          description: not found resource
  /proyecto-academico/{id}/inhabilitar:
    put:
      tags:
      - proyecto-academico
      description: Inhabilitar Proyecto
      operationId: ProyectoAcademicoController.PutInhabilitarProyecto
      parameters:
      - in: path
        name: id
        description: el id del proyecto a inhabilitar
        required: true
        type: string
      - in: body
        name: body
        description: body Inhabilitar Proyecto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "400":
          description: the request contains incorrect syntax
  /proyecto-academico/{id}/registros-alta-calidad/:
    post:
      tags:
      - proyecto-academico
      description: Post a de un registro de un proyecto existente, cambia estado activo a false a los registro anteriores y crea el nuevo
      operationId: ProyectoAcademicoController.PostRegistroAltaCalidadById
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: body
        name: body
        description: body Agregar Registro content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConsultaProyectoAcademico'
        "403":
          description: :id is empty
  /proyecto-academico/coordinador:
    post:
      tags:
      - proyecto-academico
      description: Post a de un cordinador de un proyecto existente, cambia estado activo a false a los coordinadores anteriores y crea el nuevo
      operationId: ProyectoAcademicoController.PostCoordinadorById
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: body
        name: body
        description: body Agregar Registro content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConsultaProyectoAcademico'
        "403":
          description: :id is empty
  /proyecto-academico/registro/{id}:
    get:
      tags:
      - proyecto-academico
      description: get ConsultaRegistro by id
      operationId: ProyectoAcademicoController.GetOneRegistroPorId
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConsultaProyectoAcademico'
        "403":
          description: :id is empty
  /proyecto-academico/registros-calificados/:
    post:
      tags:
      - proyecto-academico
      description: Post a de un registro de un proyecto existente, cambia estado activo a false a los registro anteriores y crea el nuevo
      operationId: ProyectoAcademicoController.PostRegistroCalificadoById
      parameters:
      - in: body
        name: body
        description: body Agregar Registro content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConsultaProyectoAcademico'
definitions:
  '{}':
    title: '{}'
    type: object
  models.ConsultaProyectoAcademico:
    title: ConsultaProyectoAcademico
    type: object
